# Generated by cadgen02.
import math
import FreeCAD as App
import Part

MODULES = [
  {
    "id": "M1",
    "type": "straight_pipe",
    "geometry_id": "solid_M1",
    "params": {
      "length": 100.0,
      "direction": "+X",
      "start_position": [
        0.0,
        0.0,
        0.0
      ],
      "axis": [
        1.0,
        0.0,
        0.0
      ],
      "outer_diameter": 20.0,
      "wall_thickness": 2.0,
      "end_position": [
        100.0,
        0.0,
        0.0
      ]
    },
    "ports": {
      "in": {
        "id": "M1.in",
        "position": [
          0.0,
          0.0,
          0.0
        ],
        "axis": [
          -1.0,
          -0.0,
          -0.0
        ],
        "outer_diameter": 20.0,
        "wall_thickness": 2.0,
        "connector_type": "plain"
      },
      "out": {
        "id": "M1.out",
        "position": [
          100.0,
          0.0,
          0.0
        ],
        "axis": [
          1.0,
          0.0,
          0.0
        ],
        "outer_diameter": 20.0,
        "wall_thickness": 2.0,
        "connector_type": "plain"
      }
    }
  },
  {
    "id": "M2",
    "type": "bend_pipe",
    "geometry_id": "solid_M2",
    "params": {
      "angle": 90.0,
      "turn_direction": "+Z",
      "start_position": [
        100.0,
        0.0,
        0.0
      ],
      "axis": [
        1.0,
        0.0,
        0.0
      ],
      "bend_radius": 30.0,
      "outer_diameter": 20.0,
      "wall_thickness": 2.0,
      "out_axis": [
        0.0,
        0.0,
        1.0
      ],
      "segment_resolution": 12,
      "path_points": [
        [
          100.0,
          0.0,
          0.0
        ],
        [
          103.91578576660154,
          0.0,
          0.25665415878568965
        ],
        [
          107.76457135307562,
          0.0,
          1.0222252113279495
        ],
        [
          111.4805029709527,
          0.0,
          2.2836140246613965
        ],
        [
          115.0,
          0.0,
          4.01923788646684
        ],
        [
          118.26284287026162,
          0.0,
          6.199399791262945
        ],
        [
          121.21320343559643,
          0.0,
          8.786796564403573
        ],
        [
          123.80060020873705,
          0.0,
          11.737157129738382
        ],
        [
          125.98076211353316,
          0.0,
          14.999999999999996
        ],
        [
          127.7163859753386,
          0.0,
          18.519497029047304
        ],
        [
          128.97777478867204,
          0.0,
          22.235428646924376
        ],
        [
          129.7433458412143,
          0.0,
          26.08421423339845
        ],
        [
          130.0,
          0.0,
          29.999999999999996
        ]
      ],
      "end_position": [
        130.0,
        0.0,
        29.999999999999996
      ]
    },
    "ports": {
      "in": {
        "id": "M2.in",
        "position": [
          100.0,
          0.0,
          0.0
        ],
        "axis": [
          -1.0,
          -0.0,
          -0.0
        ],
        "outer_diameter": 20.0,
        "wall_thickness": 2.0,
        "connector_type": "plain"
      },
      "out": {
        "id": "M2.out",
        "position": [
          130.0,
          0.0,
          29.999999999999996
        ],
        "axis": [
          0.0,
          0.0,
          1.0
        ],
        "outer_diameter": 20.0,
        "wall_thickness": 2.0,
        "connector_type": "plain"
      }
    }
  },
  {
    "id": "M3",
    "type": "straight_pipe",
    "geometry_id": "solid_M3",
    "params": {
      "length": 80.0,
      "direction": "+Z",
      "start_position": [
        130.0,
        0.0,
        29.999999999999996
      ],
      "axis": [
        0.0,
        0.0,
        1.0
      ],
      "outer_diameter": 20.0,
      "wall_thickness": 2.0,
      "end_position": [
        130.0,
        0.0,
        110.0
      ]
    },
    "ports": {
      "in": {
        "id": "M3.in",
        "position": [
          130.0,
          0.0,
          29.999999999999996
        ],
        "axis": [
          -0.0,
          -0.0,
          -1.0
        ],
        "outer_diameter": 20.0,
        "wall_thickness": 2.0,
        "connector_type": "plain"
      },
      "out": {
        "id": "M3.out",
        "position": [
          130.0,
          0.0,
          110.0
        ],
        "axis": [
          0.0,
          0.0,
          1.0
        ],
        "outer_diameter": 20.0,
        "wall_thickness": 2.0,
        "connector_type": "plain"
      }
    }
  }
]


def vector(values):
    return App.Vector(float(values[0]), float(values[1]), float(values[2]))


def make_tube_between(start_values, end_values, outer_diameter, wall_thickness):
    start = vector(start_values)
    end = vector(end_values)
    axis = end - start
    height = axis.Length
    if height <= 0:
        return None
    axis.normalize()
    outer_radius = float(outer_diameter) / 2.0
    outer = Part.makeCylinder(outer_radius, height, start, axis)
    if float(wall_thickness) <= 0:
        return outer
    inner_radius = max(outer_radius - float(wall_thickness), 0.001)
    inner = Part.makeCylinder(inner_radius, height + 2.0, start - axis, axis)
    return outer.cut(inner)


def make_reducer(module):
    params = module["params"]
    start = vector(params["start_position"])
    end = vector(params["end_position"])
    axis = end - start
    height = axis.Length
    if height <= 0:
        return None
    axis.normalize()
    outer = Part.makeCone(
        float(params["diameter_in"]) / 2.0,
        float(params["diameter_out"]) / 2.0,
        height,
        start,
        axis,
    )
    inner = Part.makeCone(
        max(float(params["diameter_in"]) / 2.0 - float(params["wall_thickness_in"]), 0.001),
        max(float(params["diameter_out"]) / 2.0 - float(params["wall_thickness_out"]), 0.001),
        height + 2.0,
        start - axis,
        axis,
    )
    return outer.cut(inner)


def make_cap(module):
    params = module["params"]
    start = vector(params["start_position"])
    axis = vector(params["axis"])
    axis.normalize()
    outer_radius = float(params["outer_diameter"]) / 2.0
    thickness = float(params.get("cap_thickness", params["wall_thickness"]))
    return Part.makeCylinder(outer_radius, thickness, start, axis)


def make_module(module):
    params = module["params"]
    kind = module["type"]
    if kind in ("straight_pipe", "connector_pipe"):
        return make_tube_between(
            params["start_position"],
            params["end_position"],
            params["outer_diameter"],
            params["wall_thickness"],
        )
    if kind == "bend_pipe":
        points = params["path_points"]
        segments = []
        for index in range(len(points) - 1):
            segment = make_tube_between(
                points[index],
                points[index + 1],
                params["outer_diameter"],
                params["wall_thickness"],
            )
            if segment is not None:
                segments.append(segment)
        if not segments:
            return None
        result = segments[0]
        for segment in segments[1:]:
            result = result.fuse(segment)
        return result
    if kind == "reducer_pipe":
        return make_reducer(module)
    if kind == "junction_pipe":
        shapes = []
        trunk = make_tube_between(
            params["start_position"],
            params["trunk_end"],
            params["outer_diameter"],
            params["wall_thickness"],
        )
        if trunk is not None:
            shapes.append(trunk)
        for key, value in params.items():
            if key.startswith("branch_") and key.endswith("_end"):
                branch = make_tube_between(
                    params["start_position"],
                    value,
                    params["outer_diameter"],
                    params["wall_thickness"],
                )
                if branch is not None:
                    shapes.append(branch)
        if not shapes:
            return None
        result = shapes[0]
        for shape in shapes[1:]:
            result = result.fuse(shape)
        return result
    if kind == "cap_pipe":
        return make_cap(module)
    return None


doc = App.ActiveDocument or App.newDocument("CadGenPipe")
shapes = []
for module in MODULES:
    shape = make_module(module)
    if shape is not None:
        shapes.append(shape)

if shapes:
    assembly = shapes[0]
    for shape in shapes[1:]:
        assembly = assembly.fuse(shape)
    obj = doc.addObject("Part::Feature", "PipeAssembly")
    obj.Shape = assembly
    doc.recompute()
