# Generated by cadgen02. Candidate build only; publishing is a separate commit phase.
import json
import math
import hashlib
import FreeCAD as App
import Part

PAYLOAD = json.loads('{"generator_version":"cadgen02-freecad-v17","state_id":"S1","state_version":1,"contract_digest":"notion-report-live-freecad-experiment","modeling_tolerance":0.0001,"root_port":{"id":"START","position":[0.0,0.0,0.0],"axis":[1.0,0.0,0.0],"outer_diameter":20.0,"wall_thickness":2.0,"connector_type":"plain","connector_gender":"neutral","connector_standard":null},"modules":[{"id":"M1","type":"transition","schema_version":2,"geometry_id":"solid_M1","params":{"section_source":"inherit_target","diameter_out":12.0,"wall_thickness_out":1.5,"length":75.0,"offset":[0.0,6.0,0.0],"start_position":[0.0,0.0,0.0],"axis":[1.0,0.0,0.0],"outer_diameter":20.0,"wall_thickness":2.0,"diameter_in":20.0,"wall_thickness_in":2.0,"connector_type_out":"plain","connector_gender_out":"neutral","connector_standard_out":null,"end_position":[75.0,6.0,0.0]},"ports":{"in":{"id":"M1.in","position":[0.0,0.0,0.0],"axis":[-1.0,-0.0,-0.0],"outer_diameter":20.0,"wall_thickness":2.0,"connector_type":"plain","connector_gender":"neutral","connector_standard":null},"out":{"id":"M1.out","position":[75.0,6.0,0.0],"axis":[1.0,0.0,0.0],"outer_diameter":12.0,"wall_thickness":1.5,"connector_type":"plain","connector_gender":"neutral","connector_standard":null}},"input_bindings":{"in":"START"}}],"open_ports":[{"id":"M1.out","position":[75.0,6.0,0.0],"axis":[1.0,0.0,0.0],"outer_diameter":12.0,"wall_thickness":1.5,"connector_type":"plain","connector_gender":"neutral","connector_standard":null}],"connection_edges":[{"edge_id":"E1","port_a_id":"START","port_b_id":"M1.in","action_id":"A1","position_error":0.0,"anti_parallel_axis_dot":1.0,"axis_angle_error":0.0,"od_error":0.0,"id_error":0.0,"wall_error":0.0,"outer_rim_error":0.0,"inner_rim_error":0.0,"connector_type_match":true,"connector_gender_match":true,"connector_standard_match":true,"engagement":0.0}]}')
MODULES = PAYLOAD["modules"]
CANDIDATE_DOCUMENT = 'CadGenCandidate_primitive_transition_changed_eccentric_1_1_da28bd7c3e2c'
PAYLOAD_DIGEST = 'da28bd7c3e2c879ceeb481bb16ff4d0c751550858eff5ea2f80372677ccbc8e4'
VALIDATION_SCHEMA_VERSION = 3
MODELING_TOLERANCE = 0.0001
GENERATOR_VERSION = 'cadgen02-freecad-v17'
RUN_ID = 'primitive_transition_changed_eccentric'
ATTEMPT_ID = 1
SPLINE_HANDLE_FACTOR_CACHE = {}


def vector(values):
    return App.Vector(float(values[0]), float(values[1]), float(values[2]))


def shape_fingerprint(shape):
    raw = shape.exportBrepToString()
    if not isinstance(raw, str) or not raw:
        raise ValueError("candidate B-Rep serialization is unavailable")
    return hashlib.sha256(raw.encode("utf-8")).hexdigest()


def vector_json(value):
    return [float(value.x), float(value.y), float(value.z)]


def normalized(value):
    result = App.Vector(value.x, value.y, value.z)
    if result.Length <= 1e-12:
        raise ValueError("zero-length direction")
    result.normalize()
    return result


def segment_distance(first_start, first_end, second_start, second_end):
    u = first_end - first_start
    v = second_end - second_start
    w = first_start - second_start
    a = u.dot(u)
    b = u.dot(v)
    c = v.dot(v)
    d = u.dot(w)
    e = v.dot(w)
    denominator = a * c - b * b
    epsilon = 1e-24
    if a <= epsilon and c <= epsilon:
        return float(w.Length)
    if a <= epsilon:
        first_parameter = 0.0
        second_parameter = max(0.0, min(1.0, e / c))
    elif c <= epsilon:
        second_parameter = 0.0
        first_parameter = max(0.0, min(1.0, -d / a))
    elif denominator <= 64.0 * math.ulp(1.0) * a * c:
        def point_segment(point, start, end):
            segment = end - start
            squared = segment.dot(segment)
            if squared <= epsilon:
                return float((point - start).Length)
            parameter = max(
                0.0,
                min(1.0, (point - start).dot(segment) / squared),
            )
            return float((point - (start + segment * parameter)).Length)
        return min(
            point_segment(first_start, second_start, second_end),
            point_segment(first_end, second_start, second_end),
            point_segment(second_start, first_start, first_end),
            point_segment(second_end, first_start, first_end),
        )
    else:
        first_parameter = max(
            0.0,
            min(1.0, (b * e - c * d) / denominator),
        )
        second_parameter = (b * first_parameter + e) / c
        if second_parameter < 0.0:
            second_parameter = 0.0
            first_parameter = max(0.0, min(1.0, -d / a))
        elif second_parameter > 1.0:
            second_parameter = 1.0
            first_parameter = max(0.0, min(1.0, (b - d) / a))
    closest_first = first_start + u * first_parameter
    closest_second = second_start + v * second_parameter
    return float((closest_first - closest_second).Length)


def perpendicular(value):
    axis = normalized(value)
    candidates = [App.Vector(0, 0, 1), App.Vector(0, 1, 0), App.Vector(1, 0, 0)]
    for candidate in candidates:
        result = axis.cross(candidate)
        if result.Length > 1e-9:
            return normalized(result)
    raise ValueError("could not derive perpendicular component axis")


def safe_radius(value):
    result = float(value)
    if result <= MODELING_TOLERANCE:
        raise ValueError("radius is below modeling tolerance")
    return result


def inner_radius(outer_diameter, wall_thickness):
    return safe_radius(float(outer_diameter) / 2.0 - float(wall_thickness))


def make_circle_wire(radius, center, normal):
    return Part.Wire([Part.makeCircle(safe_radius(radius), center, normalized(normal))])


def make_spline_wire(
    points,
    initial_tangent=None,
    final_tangent=None,
    return_handle_factors=False,
):
    """Build a waypoint-interpolating, endpoint-tangent-safe cubic spline.

    OCC's global ``BSplineCurve.interpolate`` can introduce tight endpoint
    loops when endpoint tangent constraints are combined with chord-length
    parameterization.  A chain of cubic Bezier spans is the equivalent clamped
    piecewise B-spline representation, while making every waypoint and endpoint
    tangent explicit.  Shared node handles use one direction and magnitude on
    both sides, so joins are C1 rather than merely visually close.
    """
    vectors = [vector(point) for point in points]
    if len(vectors) < 2:
        raise ValueError("spline path needs at least two points")
    chords = [float((right - left).Length) for left, right in zip(vectors, vectors[1:])]
    if any(length <= MODELING_TOLERANCE for length in chords):
        raise ValueError("spline path contains coincident or near-coincident waypoints")

    tangents = [
        normalized(vector(initial_tangent))
        if initial_tangent is not None
        else normalized(vectors[1] - vectors[0])
    ]
    for index in range(1, len(vectors) - 1):
        incoming = normalized(vectors[index] - vectors[index - 1])
        outgoing = normalized(vectors[index + 1] - vectors[index])
        bisector = incoming + outgoing
        if bisector.Length <= 1e-9:
            raise ValueError(
                "spline waypoint forms a 180-degree cusp; add separated turning waypoints"
            )
        tangents.append(normalized(bisector))
    tangents.append(
        normalized(vector(final_tangent))
        if final_tangent is not None
        else normalized(vectors[-1] - vectors[-2])
    )

    # The LLM owns waypoint placement and endpoint directions. Handle magnitude
    # is a dependent kernel parameter: optimize it deterministically for the
    # largest sampled minimum curvature radius while keeping every handle local
    # to adjacent chord scale. This avoids both a one-size-fits-all tension and
    # case-specific waypoint rewriting.
    local_scales = [chords[0]]
    local_scales.extend(
        min(chords[index - 1], chords[index])
        for index in range(1, len(vectors) - 1)
    )
    local_scales.append(chords[-1])
    cache_key = (
        tuple(
            tuple(round(float(component), 12) for component in vector_json(point))
            for point in vectors
        ),
        tuple(
            tuple(round(float(component), 12) for component in vector_json(tangent))
            for tangent in tangents
        ),
    )

    def sampled_minimum_radius(factors):
        handles = [
            float(factor) * float(scale)
            for factor, scale in zip(factors, local_scales)
        ]
        maximum_curvature = 0.0
        for index in range(len(vectors) - 1):
            p0 = vectors[index]
            p1 = p0 + tangents[index] * handles[index]
            p3 = vectors[index + 1]
            p2 = p3 - tangents[index + 1] * handles[index + 1]
            for sample_index in range(33):
                parameter = sample_index / 32.0
                complement = 1.0 - parameter
                first_derivative = (
                    (p1 - p0) * (3.0 * complement * complement)
                    + (p2 - p1) * (6.0 * complement * parameter)
                    + (p3 - p2) * (3.0 * parameter * parameter)
                )
                second_derivative = (
                    (p2 - p1 * 2.0 + p0) * (6.0 * complement)
                    + (p3 - p2 * 2.0 + p1) * (6.0 * parameter)
                )
                speed = float(first_derivative.Length)
                if speed <= MODELING_TOLERANCE:
                    return 0.0
                curvature = float(
                    first_derivative.cross(second_derivative).Length
                ) / (speed ** 3)
                maximum_curvature = max(maximum_curvature, curvature)
        return (
            1.0 / maximum_curvature
            if maximum_curvature > 1e-12
            else 1e30
        )

    factors = SPLINE_HANDLE_FACTOR_CACHE.get(cache_key)
    if factors is None:
        factors = [0.4] * len(vectors)
        candidate_factors = (0.4, 0.35, 0.45, 0.3, 0.5, 0.25, 0.55)
        # Two deterministic coordinate-descent passes let endpoint and adjacent
        # node handles co-adapt without a combinatorial search.
        for _pass_index in range(2):
            for node_index in range(len(factors)):
                best_factor = factors[node_index]
                best_score = sampled_minimum_radius(factors)
                for candidate_factor in candidate_factors:
                    candidate = list(factors)
                    candidate[node_index] = candidate_factor
                    score = sampled_minimum_radius(candidate)
                    if score > best_score * (1.0 + 1e-9):
                        best_score = score
                        best_factor = candidate_factor
                factors[node_index] = best_factor
        SPLINE_HANDLE_FACTOR_CACHE[cache_key] = list(factors)
    handles = [
        float(factor) * float(scale)
        for factor, scale in zip(factors, local_scales)
    ]

    span_edges = []
    for index in range(len(vectors) - 1):
        chord_direction = normalized(vectors[index + 1] - vectors[index])
        if (
            tangents[index].dot(chord_direction) >= 1.0 - 1e-10
            and tangents[index + 1].dot(chord_direction) >= 1.0 - 1e-10
        ):
            # A cubic Bezier whose two endpoint tangents are exactly collinear
            # with its chord is analytically a straight span.  Keeping that
            # span as a degree-3 curve can make OCC's pipe builder fail with
            # NCollection_IndexedDataMap::FindFromKey/MakeSolid even though
            # every sampled curvature check is valid.  Canonicalize the
            # degenerate representation, not the LLM-authored path geometry.
            span_edges.append(Part.makeLine(vectors[index], vectors[index + 1]))
            continue
        curve = Part.BezierCurve()
        curve.setPoles([
            vectors[index],
            vectors[index] + tangents[index] * handles[index],
            vectors[index + 1] - tangents[index + 1] * handles[index + 1],
            vectors[index + 1],
        ])
        span_edges.append(curve.toBSpline().toShape())
    # Preserve each C1 Bezier/B-spline span as an edge in one continuous wire.
    # OCC's corrected-frame pipe builder can fail at a spatial inflection when
    # the same spans are merged into one high-multiplicity B-spline edge. The
    # shared tangent/handle construction above already proves C1 continuity;
    # edge boundaries give OCC stable frame restart points at the waypoints.
    wire = Part.Wire(span_edges)
    if return_handle_factors:
        return wire, [float(factor) for factor in factors]
    return wire


def make_path_wire(points, path_kind="spline", initial_tangent=None, final_tangent=None):
    vectors = [vector(point) for point in points]
    if len(vectors) < 2:
        raise ValueError("path needs at least two points")
    if path_kind == "line":
        return Part.makePolygon(vectors)
    if path_kind == "circular_arc":
        if len(vectors) < 3:
            raise ValueError("arc path needs at least three sampled points")
        middle = vectors[len(vectors) // 2]
        return Part.Wire([Part.Arc(vectors[0], middle, vectors[-1]).toShape()])
    return make_spline_wire(points, initial_tangent, final_tangent)


def make_sweep_solid(
    points,
    radius,
    path_kind="spline",
    frenet=False,
    initial_tangent=None,
    final_tangent=None,
):
    wire = make_path_wire(points, path_kind, initial_tangent, final_tangent)
    first = vector(points[0])
    tangent = (
        normalized(vector(initial_tangent))
        if initial_tangent is not None
        else normalized(vector(points[1]) - first)
    )
    profile = make_circle_wire(radius, first, tangent)
    return wire.makePipeShell([profile], True, bool(frenet))


def make_swept_tube(
    points,
    outer_radius,
    bore_radius,
    path_kind="spline",
    frenet=False,
    initial_tangent=None,
    final_tangent=None,
):
    if initial_tangent is None or final_tangent is None:
        tangent_wire = make_path_wire(
            points, path_kind, initial_tangent, final_tangent
        )
        if not tangent_wire.Edges:
            raise ValueError("path wire has no edges for endpoint tangents")
        first_edge = tangent_wire.Edges[0]
        last_edge = tangent_wire.Edges[-1]
        if initial_tangent is None:
            initial_tangent = vector_json(
                normalized(first_edge.tangentAt(first_edge.FirstParameter))
            )
        if final_tangent is None:
            final_tangent = vector_json(
                normalized(last_edge.tangentAt(last_edge.LastParameter))
            )
    outer = make_sweep_solid(
        points, outer_radius, path_kind, frenet, initial_tangent, final_tangent
    )
    bore = make_sweep_solid(
        points, bore_radius, path_kind, frenet, initial_tangent, final_tangent
    )
    # Keep the inner path as one co-terminal sweep.  Fusing tiny endpoint
    # cylinders onto an exact curved sweep creates tangential Boolean seams in
    # OCC (SelfIntersect/TooSmallEdge), even though the authored arc itself is
    # valid.  A co-terminal outer-minus-inner cut is open, closed-shell valid,
    # and preserves the analytic endpoint tangents for line, arc, and spline.
    return outer.cut(bore), outer, bore


def make_cylinder_tube(start_values, end_values, outer_radius, bore_radius):
    start = vector(start_values)
    end = vector(end_values)
    delta = end - start
    height = delta.Length
    if height <= MODELING_TOLERANCE:
        raise ValueError("zero-length tube")
    axis = normalized(delta)
    outer = Part.makeCylinder(outer_radius, height, start, axis)
    extension = max(MODELING_TOLERANCE * 20.0, bore_radius * 1e-4)
    bore = Part.makeCylinder(
        bore_radius,
        height + extension * 2.0,
        start - axis * extension,
        axis,
    )
    return outer.cut(bore), outer, bore


def make_loft_tube(params):
    start = vector(params["start_position"])
    axis = normalized(vector(params["axis"]))
    offset = vector(params.get("offset", [0.0, 0.0, 0.0]))
    axial_length = float(params["length"])
    outer_start = float(params["diameter_in"]) / 2.0
    outer_end = float(params["diameter_out"]) / 2.0
    inner_start = inner_radius(
        params["diameter_in"], params["wall_thickness_in"]
    )
    inner_end = inner_radius(
        params["diameter_out"], params["wall_thickness_out"]
    )
    outer_profiles = []
    bore_profiles = []
    for fraction in (0.0, 0.25, 0.5, 0.75, 1.0):
        # Quintic smootherstep has zero first and second derivative at both
        # mating profiles.  The intermediate loft sections therefore ease the
        # radial/eccentric change more gently than a cubic smoothstep while
        # preserving the exact authored inlet and outlet sections.
        blend = fraction ** 3 * (
            10.0 - 15.0 * fraction + 6.0 * fraction * fraction
        )
        center = (
            start
            + axis * (axial_length * fraction)
            + offset * blend
        )
        outer_radius = outer_start + (outer_end - outer_start) * blend
        bore_radius = inner_start + (inner_end - inner_start) * blend
        outer_profiles.append(make_circle_wire(outer_radius, center, axis))
        bore_profiles.append(make_circle_wire(bore_radius, center, axis))
    outer = Part.makeLoft(outer_profiles, True, False)
    bore = Part.makeLoft(bore_profiles, True, False)
    return outer.cut(bore), outer, bore


def fuse_shapes(shapes):
    result = None
    for shape in shapes:
        if shape is None:
            continue
        result = shape if result is None else result.fuse(shape)
        if result is not None:
            result = result.removeSplitter()
    if result is None:
        raise ValueError("no shape was produced")
    return result


def fillet_local_edges(shape, radius, center, max_hub_radius, terminal_points):
    selected = []
    for edge in shape.Edges:
        try:
            point = edge.CenterOfMass
            if any(
                (point - terminal).Length <= MODELING_TOLERANCE * 50.0
                for terminal in terminal_points
            ):
                continue
            edge_parameters = (
                float(edge.FirstParameter),
                (float(edge.FirstParameter) + float(edge.LastParameter)) / 2.0,
                float(edge.LastParameter),
            )
            if any(
                (edge.valueAt(parameter) - center).Length
                > float(max_hub_radius) + MODELING_TOLERANCE
                for parameter in edge_parameters
            ):
                continue
            adjacent_faces = shape.ancestorsOfType(edge, Part.Face)
            if len(adjacent_faces) < 2:
                # Exclude longitudinal surface seams and other one-face edges.
                continue
            if any(
                face.Surface.__class__.__name__ == "Plane"
                for face in adjacent_faces
            ):
                # Terminal cap/rim edges are interfaces, not hub blend contours.
                continue
            selected.append(edge)
        except Exception:
            continue
    if not selected:
        raise ValueError("no local junction edges were available for fillet")
    result = shape.makeFillet(float(radius), selected)
    if (
        result is None
        or result.isNull()
        or not result.isValid()
        or not result.isClosed()
        or len(result.Solids) != 1
        or float(result.Volume) <= MODELING_TOLERANCE ** 3
    ):
        raise ValueError(
            "exact junction fillet produced an invalid solid at radius "
            + str(float(radius))
        )
    return result


def make_junction(params, root_interface=False):
    start = vector(params["start_position"])
    outer_parts = []
    bore_parts = []
    outer_radius_in = float(params["outer_diameter"]) / 2.0
    bore_radius_in = inner_radius(params["outer_diameter"], params["wall_thickness"])
    engagement = max(MODELING_TOLERANCE * 20.0, outer_radius_in * 1e-4)
    inlet_axis = normalized(vector(params["axis"]))
    inlet_start = start
    inlet_end = start + inlet_axis * engagement
    if not root_interface:
        inlet_start = start - inlet_axis * engagement
        inlet_end = start
    _, inlet_outer, inlet_bore = make_cylinder_tube(
        vector_json(inlet_start),
        vector_json(inlet_end),
        outer_radius_in,
        bore_radius_in,
    )
    outer_parts.append(inlet_outer)
    bore_parts.append(inlet_bore)
    terminal_points = [inlet_start]
    section_contracts = [
        (
            float(params["outer_diameter"]),
            float(params["wall_thickness"]),
        )
    ]
    for outlet in params["outlets"]:
        _, outlet_outer, outlet_bore = make_cylinder_tube(
            params["start_position"],
            outlet["end_position"],
            float(outlet["outer_diameter"]) / 2.0,
            inner_radius(outlet["outer_diameter"], outlet["wall_thickness"]),
        )
        outer_parts.append(outlet_outer)
        bore_parts.append(outlet_bore)
        terminal_points.append(vector(outlet["end_position"]))
        section_contracts.append(
            (
                float(outlet["outer_diameter"]),
                float(outlet["wall_thickness"]),
            )
        )
    if params["blend_mode"] == "fillet":
        if root_interface:
            raise ValueError(
                "a filleted junction requires a positive upstream route before "
                "the hub; it cannot be placed directly on START"
            )
        blend_radius = float(params["blend_radius"])
        inner_blend_radius = float(params["inner_blend_radius"])
        max_hub_radius = float(params["max_hub_radius"])
        maximum_outer_radius = max(
            outer_diameter / 2.0
            for outer_diameter, _wall in section_contracts
        )
        minimum_wall = min(wall for _outer_diameter, wall in section_contracts)
        maximum_bore_radius = max(
            inner_radius(outer_diameter, wall)
            for outer_diameter, wall in section_contracts
        )
        outer_hub_radius = maximum_outer_radius + blend_radius
        bore_hub_radius = outer_hub_radius - minimum_wall
        if outer_hub_radius > max_hub_radius + MODELING_TOLERANCE:
            raise ValueError(
                "exact junction blend exceeds max_hub_radius: required "
                + str(outer_hub_radius)
                + ", maximum "
                + str(max_hub_radius)
            )
        if bore_hub_radius <= maximum_bore_radius + MODELING_TOLERANCE:
            raise ValueError("junction hub leaves no positive inner blend envelope")
        if inner_blend_radius >= bore_hub_radius - MODELING_TOLERANCE:
            raise ValueError("inner junction blend radius exceeds the bore hub")
        # A bounded spherical hub makes the arm intersections regular before the
        # exact rolling-ball fillets are applied. Unlike the former raw
        # cylinder-union strategy, it does not ask OCC to fillet several
        # self-splitting contours at one three-solid vertex. The bore hub is the
        # outer hub inset by the minimum authored wall, so no hub wall can be
        # thinner than the incident pipe contract.
        outer_parts.insert(0, Part.makeSphere(outer_hub_radius, start))
        bore_parts.insert(0, Part.makeSphere(bore_hub_radius, start))
    outer = fuse_shapes(outer_parts)
    bore = fuse_shapes(bore_parts)
    if params["blend_mode"] == "fillet":
        outer = fillet_local_edges(
            outer,
            params["blend_radius"],
            start,
            params["max_hub_radius"],
            terminal_points,
        )
        bore = fillet_local_edges(
            bore,
            params["inner_blend_radius"],
            start,
            params["max_hub_radius"],
            terminal_points,
        )
    shape = outer.cut(bore).removeSplitter()
    return shape, outer, bore


def make_termination(params):
    start = vector(params["start_position"])
    axis = normalized(vector(params["axis"]))
    radius = float(params["outer_diameter"]) / 2.0
    thickness = float(params["thickness"])
    if params["termination_type"] == "plug":
        radius = inner_radius(params["outer_diameter"], params["wall_thickness"])
        start = start - axis * thickness
    shape = Part.makeCylinder(radius, thickness, start, axis)
    return shape, shape, None


def make_inline_component(params):
    start = vector(params["start_position"])
    axis = normalized(vector(params["axis"]))
    length = float(params["length"])
    pipe_radius = float(params["outer_diameter"]) / 2.0
    bore_radius = inner_radius(params["outer_diameter"], params["wall_thickness"])
    body_radius = float(params["body_outer_diameter"]) / 2.0
    body_start = start + axis * float(params["body_start_offset"])
    outer = Part.makeCylinder(pipe_radius, length, start, axis)
    body = Part.makeCylinder(body_radius, float(params["body_length"]), body_start, axis)
    outer = outer.fuse(body).removeSplitter()
    component_type = params["component_type"]
    if component_type == "flange":
        radial_a = normalized(vector(params["flange_reference_axis"]))
        radial_b = normalized(axis.cross(radial_a))
        bolt_radius = float(params["flange_bolt_hole_diameter"]) / 2.0
        bolt_circle = float(params["flange_bolt_circle_diameter"]) / 2.0
        bolt_cutters = []
        for index in range(int(params["flange_bolt_count"])):
            angle = 2.0 * math.pi * index / int(params["flange_bolt_count"])
            radial = radial_a * math.cos(angle) + radial_b * math.sin(angle)
            center = body_start + radial * bolt_circle
            bolt_cutters.append(
                Part.makeCylinder(
                    bolt_radius,
                    float(params["body_length"]) + MODELING_TOLERANCE * 4.0,
                    center - axis * MODELING_TOLERANCE * 2.0,
                    axis,
                )
            )
        outer = outer.cut(fuse_shapes(bolt_cutters)).removeSplitter()
    elif component_type == "union":
        ring_length = float(params["union_ring_length"])
        ring_radius = float(params["union_ring_outer_diameter"]) / 2.0
        ring_a = Part.makeCylinder(ring_radius, ring_length, body_start, axis)
        ring_b = Part.makeCylinder(
            ring_radius,
            ring_length,
            body_start + axis * (float(params["body_length"]) - ring_length),
            axis,
        )
        outer = outer.fuse(ring_a).fuse(ring_b).removeSplitter()
    elif component_type == "valve":
        actuator_axis = normalized(vector(params["actuator_axis"]))
        actuator_origin = (
            body_start
            + axis * (float(params["body_length"]) / 2.0)
            - actuator_axis * (float(params["actuator_height"]) * 0.15)
        )
        actuator = Part.makeCylinder(
            float(params["actuator_diameter"]) / 2.0,
            float(params["actuator_height"]) * 1.15,
            actuator_origin,
            actuator_axis,
        )
        outer = outer.fuse(actuator).removeSplitter()
    extension = max(MODELING_TOLERANCE * 20.0, bore_radius * 1e-4)
    bore = Part.makeCylinder(
        bore_radius,
        length + extension * 2.0,
        start - axis * extension,
        axis,
    )
    return outer.cut(bore).removeSplitter(), outer, bore


def make_module_shape(module):
    params = module["params"]
    kind = module["type"]
    if kind in ("straight_pipe", "connector_pipe"):
        outer_radius = float(params.get("coupling_outer_diameter", params["outer_diameter"])) / 2.0
        return make_cylinder_tube(
            params["start_position"],
            params["end_position"],
            outer_radius,
            inner_radius(params["outer_diameter"], params["wall_thickness"]),
        )
    if kind == "bend_pipe":
        return make_swept_tube(
            params["path_points"],
            float(params["outer_diameter"]) / 2.0,
            inner_radius(params["outer_diameter"], params["wall_thickness"]),
            "circular_arc",
            True,
        )
    if kind == "reducer_pipe":
        return make_loft_tube(params)
    if kind == "junction_pipe":
        legacy_outlets = []
        if params.get("include_primary_outlet", True) and params.get("trunk_end") is not None:
            legacy_outlets.append({
                "end_position": params["trunk_end"],
                "outer_diameter": params["outer_diameter"],
                "wall_thickness": params["wall_thickness"],
            })
        for key, value in params.items():
            if key.startswith("branch_") and key.endswith("_end"):
                legacy_outlets.append({
                    "end_position": value,
                    "outer_diameter": params["outer_diameter"],
                    "wall_thickness": params["wall_thickness"],
                })
        migrated = dict(params)
        migrated["outlets"] = legacy_outlets
        migrated["blend_mode"] = "hard"
        migrated["blend_radius"] = max(float(params.get("blend_radius", 1.0)), MODELING_TOLERANCE)
        migrated["inner_blend_radius"] = migrated["blend_radius"]
        migrated["max_hub_radius"] = max(migrated["blend_radius"], float(params["outer_diameter"]) / 2.0)
        return make_junction(
            migrated,
            "START" in (module.get("input_bindings") or {}).values(),
        )
    if kind == "cap_pipe":
        if params.get("end_type") == "open":
            raise ValueError("legacy open-end marker has no geometry")
        migrated = dict(params)
        migrated["termination_type"] = "cap"
        migrated["thickness"] = params["cap_thickness"]
        return make_termination(migrated)
    if kind == "route":
        path_kind = params["path_kind"]
        if path_kind == "line":
            path_kind = "line"
        elif path_kind == "circular_arc":
            path_kind = "circular_arc"
        else:
            path_kind = "spline"
        return make_swept_tube(
            params["path_points"],
            float(params["outer_diameter"]) / 2.0,
            inner_radius(params["outer_diameter"], params["wall_thickness"]),
            path_kind,
            bool(params.get("frenet", False)),
            params.get("initial_tangent", params.get("axis")),
            params.get("final_tangent", params.get("terminal_axis")),
        )
    if kind == "transition":
        return make_loft_tube(params)
    if kind == "junction":
        return make_junction(
            params,
            "START" in (module.get("input_bindings") or {}).values(),
        )
    if kind == "connect_ports":
        return make_swept_tube(
            params["path_points"],
            float(params["outer_diameter"]) / 2.0,
            inner_radius(params["outer_diameter"], params["wall_thickness"]),
            params["path_kind"],
            bool(params.get("frenet", False)),
            params.get("initial_tangent"),
            params.get("final_tangent"),
        )
    if kind == "terminate":
        return make_termination(params)
    if kind == "inline_component":
        return make_inline_component(params)
    raise ValueError("unsupported module type: " + str(kind))


def centerline_check(module):
    params = module["params"]
    curve_length = None
    try:
        if params.get("path_points"):
            curve_length = float(
                make_path_wire(
                    params["path_points"],
                    params.get("path_kind", "line"),
                    params.get("initial_tangent"),
                    params.get("final_tangent"),
                ).Length
            )
        elif module["type"] == "junction":
            curve_length = sum(float(item["length"]) for item in params["outlets"])
        elif module["type"] == "transition":
            curve_length = float(
                (vector(params["end_position"]) - vector(params["start_position"])).Length
            )
        elif params.get("length") is not None:
            curve_length = float(params["length"])
        elif module["type"] == "terminate":
            curve_length = 0.0
    except Exception as exc:
        return {
            "passed": False,
            "required_radius": params.get("minimum_curvature_radius"),
            "curve_length_error": str(exc),
        }
    required_raw = params.get("minimum_curvature_radius")
    required = float(required_raw) if required_raw is not None else None
    path_kind = params.get("path_kind")
    if path_kind not in {"spline", "circular_arc"}:
        actual = (
            float(params.get("bend_radius", required))
            if required is not None
            else None
        )
        return {
            "passed": required is None or actual + MODELING_TOLERANCE >= required,
            "required_radius": required,
            "minimum_radius": actual,
            "curve_length": curve_length,
            "minimum_nonlocal_distance": None,
            "required_self_clearance": None,
        }
    try:
        optimized_handle_factors = None
        if path_kind == "spline":
            wire, optimized_handle_factors = make_spline_wire(
                params["path_points"],
                params.get("initial_tangent"),
                params.get("final_tangent"),
                return_handle_factors=True,
            )
        else:
            wire = make_path_wire(
                params["path_points"],
                path_kind,
                params.get("initial_tangent"),
                params.get("final_tangent"),
            )
        edges = list(wire.Edges)
        if not edges:
            raise ValueError("curved path wire has no edges")
        curvatures = []
        sampled_points = []
        sampled_locations = []
        join_tangent_dots = []
        samples_per_edge = (
            257
            if path_kind == "circular_arc"
            else max(
                257,
                min(1025, 64 * (len(params["path_points"]) - 1) + 1),
            )
        )
        for edge_index, edge in enumerate(edges):
            first = float(edge.FirstParameter)
            last = float(edge.LastParameter)
            if edge_index:
                previous = edges[edge_index - 1]
                previous_tangent = normalized(
                    previous.tangentAt(previous.LastParameter)
                )
                current_tangent = normalized(edge.tangentAt(first))
                join_tangent_dots.append(
                    float(previous_tangent.dot(current_tangent))
                )
            for sample_index in range(samples_per_edge):
                if edge_index and sample_index == 0:
                    continue
                parameter = first + (last - first) * sample_index / (
                    samples_per_edge - 1
                )
                curvature = abs(float(edge.curvatureAt(parameter)))
                if not math.isfinite(curvature):
                    raise ValueError("non-finite curve curvature sample")
                curvatures.append(curvature)
                sampled_points.append(edge.valueAt(parameter))
                sampled_locations.append([edge_index, parameter])
        maximum = max(curvatures or [0.0])
        zero_curvature = maximum <= 1e-12
        minimum_radius = None if zero_curvature else 1.0 / maximum
        worst_curvature_index = (
            max(range(len(curvatures)), key=curvatures.__getitem__)
            if curvatures
            else None
        )
        minimum_radius_location = None
        minimum_radius_nearest_path_point_index = None
        curvature_repair_hint = None
        if worst_curvature_index is not None:
            worst_point = sampled_points[worst_curvature_index]
            authored_points = [vector(point) for point in params["path_points"]]
            minimum_radius_nearest_path_point_index = min(
                range(len(authored_points)),
                key=lambda index: float((authored_points[index] - worst_point).Length),
            )
            minimum_radius_location = {
                "position": vector_json(worst_point),
                "edge_parameter": sampled_locations[worst_curvature_index],
                "sample_index": worst_curvature_index,
            }
            if path_kind == "circular_arc":
                curvature_repair_hint = (
                    "The circular arc is tighter than its required curvature bound. "
                    "Increase the independent bend radius or, for connect_ports, "
                    "move the midpoint farther from the endpoint chord."
                )
            elif minimum_radius_nearest_path_point_index == 0:
                curvature_repair_hint = (
                    "The curvature peak is near the spline inlet. Add one or more "
                    "smoothing waypoints after the inlet along initial_tangent before "
                    "turning toward the required anchors; changing only final_tangent "
                    "cannot repair an inlet-local peak."
                )
            elif minimum_radius_nearest_path_point_index == len(authored_points) - 1:
                curvature_repair_hint = (
                    "The curvature peak is near the spline outlet. Add one or more "
                    "smoothing waypoints before the terminal point aligned with "
                    "final_tangent; changing only an inlet-side point cannot repair "
                    "an outlet-local peak."
                )
            else:
                curvature_repair_hint = (
                    "The curvature peak is near authored path point index "
                    + str(minimum_radius_nearest_path_point_index)
                    + ". Preserve required anchors but spread this direction change "
                    "over additional, well-separated waypoints before and after it."
                )
        curvature_passed = (
            required is None
            or zero_curvature
            or minimum_radius + MODELING_TOLERANCE >= required
        )

        segment_lengths = [
            float((right - left).Length)
            for left, right in zip(sampled_points, sampled_points[1:])
        ]
        cumulative = [0.0]
        for segment_length in segment_lengths:
            cumulative.append(cumulative[-1] + segment_length)
        outer_radius = float(params["outer_diameter"]) / 2.0
        required_self_clearance = 2.0 * outer_radius + MODELING_TOLERANCE
        local_arc_exclusion = math.pi * outer_radius
        minimum_nonlocal_distance = None
        closest_pair = None
        for left_index in range(len(sampled_points) - 1):
            for right_index in range(left_index + 2, len(sampled_points) - 1):
                intervening_arc = (
                    cumulative[right_index] - cumulative[left_index + 1]
                )
                if intervening_arc <= local_arc_exclusion:
                    continue
                separation = segment_distance(
                    sampled_points[left_index],
                    sampled_points[left_index + 1],
                    sampled_points[right_index],
                    sampled_points[right_index + 1],
                )
                if (
                    minimum_nonlocal_distance is None
                    or separation < minimum_nonlocal_distance
                ):
                    minimum_nonlocal_distance = separation
                    closest_pair = {
                        "segment_indices": [left_index, right_index],
                        "edge_parameters": [
                            sampled_locations[left_index],
                            sampled_locations[right_index],
                        ],
                        "intervening_centerline_length": intervening_arc,
                    }
        self_clearance_passed = (
            minimum_nonlocal_distance is None
            or minimum_nonlocal_distance + MODELING_TOLERANCE
            >= required_self_clearance
        )
        minimum_join_tangent_dot = min(join_tangent_dots or [1.0])
        tangent_continuity_passed = minimum_join_tangent_dot >= 1.0 - 1e-9
        endpoint_tangent_dots = None
        endpoint_tangency_passed = True
        if path_kind == "spline":
            actual_initial = normalized(
                edges[0].tangentAt(edges[0].FirstParameter)
            )
            actual_final = normalized(
                edges[-1].tangentAt(edges[-1].LastParameter)
            )
            expected_initial = normalized(vector(params["initial_tangent"]))
            expected_final = normalized(vector(params["final_tangent"]))
            endpoint_tangent_dots = {
                "initial": float(actual_initial.dot(expected_initial)),
                "final": float(actual_final.dot(expected_final)),
            }
            endpoint_tangency_passed = all(
                value >= 1.0 - 1e-9
                for value in endpoint_tangent_dots.values()
            )
        return {
            "passed": (
                curvature_passed
                and self_clearance_passed
                and tangent_continuity_passed
                and endpoint_tangency_passed
            ),
            "required_radius": required,
            "minimum_radius": minimum_radius,
            "minimum_radius_location": minimum_radius_location,
            "minimum_radius_nearest_path_point_index": (
                minimum_radius_nearest_path_point_index
            ),
            "curvature_repair_hint": curvature_repair_hint,
            "zero_curvature": zero_curvature,
            "sample_count": len(curvatures),
            "curvature_method": "dense_piecewise_curve_sampling",
            "curvature_proof": "sampled_not_global_extremum",
            "curve_length": curve_length,
            "optimized_handle_factors": optimized_handle_factors,
            "minimum_join_tangent_dot": minimum_join_tangent_dot,
            "tangent_continuity_passed": tangent_continuity_passed,
            "endpoint_tangent_dots": endpoint_tangent_dots,
            "endpoint_tangency_passed": endpoint_tangency_passed,
            "minimum_nonlocal_distance": minimum_nonlocal_distance,
            "required_self_clearance": required_self_clearance,
            "self_clearance_passed": self_clearance_passed,
            "self_clearance_closest_pair": closest_pair,
            "self_clearance_method": "dense_nonlocal_segment_sampling",
        }
    except Exception as exc:
        return {
            "passed": False,
            "required_radius": required,
            "error": str(exc),
        }


def shape_check(shape):
    bounds = shape.BoundBox
    result = {
        "is_null": bool(shape.isNull()),
        "is_valid": bool(shape.isValid()),
        "is_closed": bool(shape.isClosed()),
        "solid_count": len(shape.Solids),
        "volume": float(shape.Volume),
        "bounds": {
            "minimum": [float(bounds.XMin), float(bounds.YMin), float(bounds.ZMin)],
            "maximum": [float(bounds.XMax), float(bounds.YMax), float(bounds.ZMax)],
        },
        "bop_errors": [],
        "shape_check_mode": "topology_without_global_bop_argument_analysis",
    }
    try:
        # ``check(True)`` invokes OCC's global BOP argument analyzer. Repeating
        # it for every module plus the outer, bore, and final networks is both
        # redundant with the explicit overlap/clearance probes below and has
        # been observed to crash or stall FreeCAD on valid high-order B-spline
        # sweep surfaces. ``isValid`` plus topology check(False) remains strict
        # about the B-Rep itself; the specialized checks cover nonlocal tube
        # self-clearance and inter-module intersection.
        raw = shape.check(False)
        if raw:
            result["bop_errors"] = [str(item) for item in raw]
    except Exception as exc:
        result["bop_errors"] = ["check_exception: " + str(exc)]
    result["passed"] = (
        not result["is_null"]
        and result["is_valid"]
        and result["is_closed"]
        and result["solid_count"] == 1
        and result["volume"] > MODELING_TOLERANCE ** 3
        and not result["bop_errors"]
    )
    return result


def sample_hollow_section(
    shape, position, axis, outer_radius, bore_radius, *, check_outer=True
):
    axis = normalized(axis)
    radial_a = perpendicular(axis)
    radial_b = normalized(axis.cross(radial_a))
    wall_radius = (float(outer_radius) + float(bore_radius)) / 2.0
    outside_radius = float(outer_radius) + max(
        MODELING_TOLERANCE * 20.0,
        (float(outer_radius) - float(bore_radius)) * 0.25,
    )
    failures = []
    for sample_index in range(8):
        angle = 2.0 * math.pi * sample_index / 8.0
        radial = radial_a * math.cos(angle) + radial_b * math.sin(angle)
        wall_point = position + radial * wall_radius
        if not bool(shape.isInside(wall_point, MODELING_TOLERANCE, True)):
            failures.append({
                "sample": sample_index,
                "kind": "missing_wall_material",
            })
        if check_outer:
            outside_point = position + radial * outside_radius
            if bool(shape.isInside(outside_point, MODELING_TOLERANCE, True)):
                failures.append({
                    "sample": sample_index,
                    "kind": "material_outside_outer_radius",
                })
    if bool(shape.isInside(position, MODELING_TOLERANCE, True)):
        failures.append({"sample": "center", "kind": "blocked_bore"})
    return failures


if CANDIDATE_DOCUMENT in App.listDocuments():
    App.closeDocument(CANDIDATE_DOCUMENT)
doc = App.newDocument(CANDIDATE_DOCUMENT)

module_shapes = {}
module_outer_shapes = {}
module_bore_shapes = {}
module_checks = {}
centerline_checks = {}
module_errors = []
for module in MODULES:
    module_id = module.get("id")
    if module_id is not None:
        try:
            # Centerline diagnostics do not depend on a successful solid sweep.
            # Evaluate them first so OCC construction failures still report the
            # actual curvature, tangency, and nonlocal-clearance evidence needed
            # for a useful repair instead of only MakePipeShell::MakeSolid.
            centerline_checks[module_id] = centerline_check(module)
        except Exception as exc:
            centerline_checks[module_id] = {
                "passed": False,
                "error": "centerline validation failed: " + str(exc),
            }
    try:
        shape, outer, bore = make_module_shape(module)
        obj = doc.addObject("Part::Feature", module["geometry_id"])
        obj.Label = module["id"] + " " + module["type"]
        if obj.ViewObject is not None:
            # Candidate documents are validation-only. Hide before assigning a
            # high-order shape so Coin/OCC does not start asynchronous meshing
            # for every overlapping module while Boolean work is still active.
            obj.ViewObject.Visibility = False
        obj.Shape = shape
        obj.addProperty("App::PropertyString", "CadGenModuleId")
        obj.CadGenModuleId = module["id"]
        obj.addProperty("App::PropertyString", "CadGenPayloadDigest")
        obj.CadGenPayloadDigest = PAYLOAD_DIGEST
        if module["type"] == "inline_component":
            obj.addProperty("App::PropertyString", "CadGenComponentType")
            obj.CadGenComponentType = str(module["params"]["component_type"])
        module_shapes[module["id"]] = shape
        module_outer_shapes[module["id"]] = outer
        if bore is not None:
            module_bore_shapes[module["id"]] = bore
        module_checks[module["id"]] = shape_check(shape)
    except Exception as exc:
        error = str(exc)
        module_errors.append({"module_id": module_id, "error": error})
        if module_id is not None:
            module_checks[module_id] = {
                "passed": False,
                "error": error,
            }

assembly = None
assembly_check = {
    "is_null": True,
    "is_valid": False,
    "is_closed": False,
    "solid_count": 0,
    "volume": 0.0,
    "bop_errors": ["assembly not built"],
    "passed": False,
}
overlaps = []
assembly_errors = []
outer_network_check = {"passed": False, "reason": "outer network not built"}
bore_network_check = {"passed": False, "reason": "bore network not built"}
if not module_errors and module_shapes:
    outer_network = None
    flow_bore_network = None
    try:
        outer_network = fuse_shapes(list(module_outer_shapes.values()))
        outer_network_check = shape_check(outer_network)
    except Exception as exc:
        assembly_errors.append({"stage": "outer_network_fuse", "error": str(exc)})
    if module_bore_shapes:
        try:
            bore_network = fuse_shapes(list(module_bore_shapes.values()))
            flow_bore_network = bore_network
            for module in MODULES:
                if module["type"] not in ("terminate", "cap_pipe"):
                    continue
                seal = module_shapes.get(module["id"])
                if seal is not None:
                    params = module["params"]
                    start = vector(params["start_position"])
                    axis = normalized(vector(params["axis"]))
                    bore_radius = inner_radius(
                        params["outer_diameter"], params["wall_thickness"]
                    )
                    termination_type = params.get("termination_type", "cap")
                    thickness = float(
                        params.get("thickness", params.get("cap_thickness", 0.0))
                    )
                    trim = max(MODELING_TOLERANCE * 50.0, bore_radius * 1e-3)
                    low = -trim if termination_type == "cap" else -thickness - trim
                    high = thickness + trim if termination_type == "cap" else trim
                    seal_with_trim = seal.fuse(
                        Part.makeCylinder(
                            bore_radius,
                            high - low,
                            start + axis * low,
                            axis,
                        )
                    )
                    flow_bore_network = flow_bore_network.cut(
                        seal_with_trim
                    ).removeSplitter()
            bore_network_check = shape_check(flow_bore_network)
            bore_network_check["passed"] = bool(
                bore_network_check.get("passed")
                and int(bore_network_check.get("solid_count", 0)) == 1
            )
        except Exception as exc:
            assembly_errors.append({"stage": "bore_network_fuse", "error": str(exc)})
    try:
        if outer_network is None:
            raise ValueError("outer network is unavailable")
        assembly = (
            outer_network.cut(flow_bore_network).removeSplitter()
            if flow_bore_network is not None
            else outer_network
        )
        assembly_check = shape_check(assembly)
        if flow_bore_network is not None:
            # ``assembly`` is defined immediately above as
            # ``outer_network.cut(flow_bore_network)``. Re-running a global
            # common() between those coincident high-order B-spline surfaces is
            # logically redundant and can trap OCC's face/face intersector for
            # minutes. Shape validity, a one-solid bore network, terminal probes,
            # and dense internal annular-section samples provide independent
            # evidence without repeating that pathological Boolean.
            bore_network_check["assembly_intrusion_volume"] = 0.0
            bore_network_check["assembly_intrusion_allowance"] = max(
                MODELING_TOLERANCE ** 3,
                float(flow_bore_network.Volume) * 1e-8,
            )
            bore_network_check["intrusion_check_method"] = (
                "outer_minus_bore_construction_invariant"
            )
            bore_network_check["intrusion_module_ids"] = []
            bore_network_check["passed"] = bool(bore_network_check.get("passed"))
    except Exception as exc:
        assembly_errors.append({"stage": "assembly_global_bore_cut", "error": str(exc)})
    module_ids = list(module_shapes)
    module_by_id = {module["id"]: module for module in MODULES}
    adjacency = set()
    for module in MODULES:
        for bound in (module.get("input_bindings") or {}).values():
            if "." in bound:
                adjacency.add(tuple(sorted((module["id"], bound.split(".", 1)[0]))))
    for index, left_id in enumerate(module_ids):
        for right_id in module_ids[index + 1:]:
            pair = tuple(sorted((left_id, right_id)))
            # OCC Boolean common()은 고차 spline solid에서 가장 비싼 검사다.
            # AABB가 modeling tolerance까지 고려해 분리되어 있으면 실제 solid도
            # 겹칠 수 없으므로 정확도를 잃지 않고 Boolean 후보에서 제외한다.
            left_box = module_shapes[left_id].BoundBox
            right_box = module_shapes[right_id].BoundBox
            boxes_disjoint = (
                left_box.XMax < right_box.XMin - MODELING_TOLERANCE
                or right_box.XMax < left_box.XMin - MODELING_TOLERANCE
                or left_box.YMax < right_box.YMin - MODELING_TOLERANCE
                or right_box.YMax < left_box.YMin - MODELING_TOLERANCE
                or left_box.ZMax < right_box.ZMin - MODELING_TOLERANCE
                or right_box.ZMax < left_box.ZMin - MODELING_TOLERANCE
            )
            if boxes_disjoint:
                continue
            allowed_volume = MODELING_TOLERANCE ** 3
            if pair in adjacency:
                for child_id, parent_id in ((left_id, right_id), (right_id, left_id)):
                    child = module_by_id[child_id]
                    bound_parents = {
                        value.split(".", 1)[0]
                        for value in (child.get("input_bindings") or {}).values()
                        if "." in value
                    }
                    if parent_id in bound_parents and child["type"] == "junction":
                        params = child["params"]
                        outer_radius = float(params["outer_diameter"]) / 2.0
                        bore_radius = inner_radius(
                            params["outer_diameter"], params["wall_thickness"]
                        )
                        engagement = max(
                            MODELING_TOLERANCE * 20.0,
                            outer_radius * 1e-4,
                        )
                        if params.get("blend_mode") == "fillet":
                            # A smooth hub intentionally owns a bounded overlap
                            # with its immediately upstream connected module.
                            # Non-adjacent pairs retain the strict global limit.
                            engagement = max(
                                engagement,
                                float(params["max_hub_radius"]),
                            )
                        allowed_volume = max(
                            allowed_volume,
                            math.pi
                            * (outer_radius ** 2 - bore_radius ** 2)
                            * engagement
                            * 1.25,
                        )
            try:
                volume = float(module_shapes[left_id].common(module_shapes[right_id]).Volume)
            except Exception as exc:
                overlaps.append({"module_ids": [left_id, right_id], "error": str(exc)})
                continue
            if volume > allowed_volume:
                overlaps.append({
                    "module_ids": [left_id, right_id],
                    "adjacent": pair in adjacency,
                    "common_volume": volume,
                    "allowed_volume": allowed_volume,
                })
    if assembly is not None:
        try:
            assembly_obj = doc.addObject("Part::Feature", "PipeAssembly")
            if assembly_obj.ViewObject is not None:
                assembly_obj.ViewObject.Visibility = False
            assembly_obj.Shape = assembly
            assembly_obj.addProperty("App::PropertyString", "CadGenPayloadDigest")
            assembly_obj.CadGenPayloadDigest = PAYLOAD_DIGEST
            assembly_obj.addProperty("App::PropertyString", "CadGenStateId")
            assembly_obj.CadGenStateId = PAYLOAD["state_id"]
            for module_id in module_ids:
                module_view = doc.getObject("solid_" + module_id).ViewObject
                if module_view is not None:
                    module_view.Visibility = False
        except Exception as exc:
            assembly_errors.append({"stage": "assembly_object", "error": str(exc)})

try:
    doc.recompute()
except Exception as exc:
    assembly_errors.append({"stage": "document_recompute", "error": str(exc)})

connection_failures = []
for edge in PAYLOAD.get("connection_edges", []):
    if (
        float(edge.get("position_error", 0.0)) > MODELING_TOLERANCE
        or float(edge.get("anti_parallel_axis_dot", 0.0)) < 0.9999
        or float(edge.get("od_error", 0.0)) > MODELING_TOLERANCE
        or float(edge.get("id_error", 0.0)) > MODELING_TOLERANCE
        or float(edge.get("wall_error", 0.0)) > MODELING_TOLERANCE
        or float(edge.get("outer_rim_error", float("inf"))) > MODELING_TOLERANCE
        or float(edge.get("inner_rim_error", float("inf"))) > MODELING_TOLERANCE
        or not bool(edge.get("connector_type_match", False))
        or not bool(edge.get("connector_gender_match", False))
        or not bool(edge.get("connector_standard_match", False))
    ):
        connection_failures.append(edge)

terminal_bore_failures = []
anchored_inlet_bore_failures = []
termination_seal_failures = []
if assembly is not None:
    for port in PAYLOAD.get("open_ports", []):
        try:
            position = vector(port["position"])
            axis = normalized(vector(port["axis"]))
            bore_radius = inner_radius(
                port["outer_diameter"], port["wall_thickness"]
            )
            probe_radius = max(MODELING_TOLERANCE * 10.0, bore_radius * 0.35)
            probe_length = max(MODELING_TOLERANCE * 50.0, bore_radius * 0.1)
            probe = Part.makeCylinder(
                probe_radius,
                probe_length,
                position - axis * probe_length,
                axis,
            )
            blocked_volume = float(assembly.common(probe).Volume)
            allowance = max(MODELING_TOLERANCE ** 3, float(probe.Volume) * 1e-5)
            if blocked_volume > allowance:
                terminal_bore_failures.append({
                    "port_id": port["id"],
                    "blocked_volume": blocked_volume,
                    "allowance": allowance,
                })
        except Exception as exc:
            terminal_bore_failures.append({"port_id": port.get("id"), "error": str(exc)})
    root_port = PAYLOAD.get("root_port")
    root_is_open_bore = bool(
        root_port
        and MODULES
        and MODULES[0]["type"] not in ("terminate", "cap_pipe")
    )
    if root_is_open_bore:
        try:
            position = vector(root_port["position"])
            axis = normalized(vector(root_port["axis"]))
            bore_radius = inner_radius(
                root_port["outer_diameter"], root_port["wall_thickness"]
            )
            probe_radius = max(MODELING_TOLERANCE * 10.0, bore_radius * 0.35)
            probe_length = max(MODELING_TOLERANCE * 50.0, bore_radius * 0.1)
            if MODULES[0]["type"] in ("junction", "junction_pipe"):
                first_params = MODULES[0]["params"]
                outer_radius = float(first_params["outer_diameter"]) / 2.0
                engagement = max(
                    MODELING_TOLERANCE * 20.0,
                    outer_radius * 1e-4,
                )
                probe_length = min(probe_length, engagement * 0.75)
            probe = Part.makeCylinder(
                probe_radius,
                probe_length,
                position,
                axis,
            )
            blocked_volume = float(assembly.common(probe).Volume)
            allowance = max(MODELING_TOLERANCE ** 3, float(probe.Volume) * 1e-5)
            if blocked_volume > allowance:
                anchored_inlet_bore_failures.append({
                    "port_id": root_port["id"],
                    "blocked_volume": blocked_volume,
                    "allowance": allowance,
                })
        except Exception as exc:
            anchored_inlet_bore_failures.append({
                "port_id": root_port.get("id"), "error": str(exc)
            })
    for module in MODULES:
        if module["type"] != "terminate":
            continue
        params = module["params"]
        try:
            position = vector(params["start_position"])
            axis = normalized(vector(params["axis"]))
            radius = inner_radius(params["outer_diameter"], params["wall_thickness"])
            probe_radius = max(MODELING_TOLERANCE * 10.0, radius * 0.35)
            probe_length = min(
                float(params["thickness"]) * 0.5,
                max(MODELING_TOLERANCE * 50.0, radius * 0.1),
            )
            origin = (
                position
                if params["termination_type"] == "cap"
                else position - axis * probe_length
            )
            probe = Part.makeCylinder(probe_radius, probe_length, origin, axis)
            filled_volume = float(assembly.common(probe).Volume)
            required_volume = float(probe.Volume) * 0.99
            if filled_volume + MODELING_TOLERANCE ** 3 < required_volume:
                termination_seal_failures.append({
                    "module_id": module["id"],
                    "filled_volume": filled_volume,
                    "required_volume": required_volume,
                })
        except Exception as exc:
            termination_seal_failures.append({
                "module_id": module.get("id"), "error": str(exc)
            })

wall_section_failures = []
sampled_internal_section_count = 0
sampled_internal_sections_by_module = {}
for module in MODULES:
    if module["type"] in ("terminate", "cap_pipe"):
        continue
    shape = module_shapes.get(module["id"])
    if shape is None:
        wall_section_failures.append({
            "module_id": module.get("id"), "error": "module shape is missing"
        })
        continue
    for local_name, port in (module.get("ports") or {}).items():
        if module["type"] == "junction" and local_name == "in":
            # The inlet plane is the hub center, not an annular free section;
            # intentional branch bores invalidate a simple ring occupancy test.
            continue
        try:
            position = vector(port["position"])
            axis = normalized(vector(port["axis"]))
            radial_a = perpendicular(axis)
            radial_b = normalized(axis.cross(radial_a))
            outer_radius = float(port["outer_diameter"]) / 2.0
            bore_radius = inner_radius(
                port["outer_diameter"], port["wall_thickness"]
            )
            wall_radius = (outer_radius + bore_radius) / 2.0
            outside_radius = outer_radius + max(
                MODELING_TOLERANCE * 20.0,
                float(port["wall_thickness"]) * 0.25,
            )
            check_outer = True
            if module["type"] == "inline_component":
                params = module["params"]
                body_start = float(params["body_start_offset"])
                body_end = body_start + float(params["body_length"])
                if local_name == "in" and body_start <= MODELING_TOLERANCE:
                    check_outer = False
                if local_name == "out" and abs(
                    body_end - float(params["length"])
                ) <= MODELING_TOLERANCE:
                    check_outer = False
            failed_samples = []
            for sample_index in range(8):
                angle = 2.0 * math.pi * sample_index / 8.0
                radial = radial_a * math.cos(angle) + radial_b * math.sin(angle)
                wall_point = position + radial * wall_radius
                outside_point = position + radial * outside_radius
                if not bool(shape.isInside(wall_point, MODELING_TOLERANCE, True)):
                    failed_samples.append({
                        "sample": sample_index,
                        "kind": "missing_wall_material",
                    })
                if check_outer and bool(
                    shape.isInside(outside_point, MODELING_TOLERANCE, True)
                ):
                    failed_samples.append({
                        "sample": sample_index,
                        "kind": "material_outside_outer_radius",
                    })
            if bool(shape.isInside(position, MODELING_TOLERANCE, True)):
                failed_samples.append({"sample": "center", "kind": "blocked_bore"})
            if failed_samples:
                wall_section_failures.append({
                    "module_id": module["id"],
                    "port": local_name,
                    "authored_wall_thickness": float(port["wall_thickness"]),
                    "failures": failed_samples,
                })
        except Exception as exc:
            wall_section_failures.append({
                "module_id": module.get("id"),
                "port": local_name,
                "error": str(exc),
            })

for module in MODULES:
    module_id = module.get("id")
    shape = module_shapes.get(module_id)
    if shape is None:
        continue
    params = module["params"]
    kind = module["type"]
    try:
        candidates = []
        if kind in ("route", "connect_ports", "bend_pipe"):
            points = [vector(point) for point in params.get("path_points", [])]
            if len(points) >= 2:
                if params.get("path_kind") == "spline" and len(points) > 2:
                    wire = make_spline_wire(
                        params["path_points"],
                        params.get("initial_tangent"),
                        params.get("final_tangent"),
                    )
                    edges = list(wire.Edges)
                    edge_lengths = [float(edge.Length) for edge in edges]
                    total_length = sum(edge_lengths)
                    for index in range(1, 8):
                        target_length = total_length * index / 8.0
                        traversed = 0.0
                        edge = edges[-1]
                        local_fraction = 1.0
                        for candidate, edge_length in zip(edges, edge_lengths):
                            if target_length <= traversed + edge_length:
                                edge = candidate
                                local_fraction = (
                                    (target_length - traversed) / edge_length
                                    if edge_length > MODELING_TOLERANCE
                                    else 0.0
                                )
                                break
                            traversed += edge_length
                        parameter = float(edge.FirstParameter) + (
                            float(edge.LastParameter) - float(edge.FirstParameter)
                        ) * local_fraction
                        candidates.append((
                            "spline_sample_" + str(index),
                            edge.valueAt(parameter),
                            edge.tangentAt(parameter),
                            float(params["outer_diameter"]) / 2.0,
                            inner_radius(
                                params["outer_diameter"], params["wall_thickness"]
                            ),
                        ))
                else:
                    stride = max(1, int(math.ceil((len(points) - 1) / 16.0)))
                    for index in range(0, len(points) - 1, stride):
                        candidates.append((
                            "path_segment_" + str(index),
                            (points[index] + points[index + 1]) * 0.5,
                            points[index + 1] - points[index],
                            float(params["outer_diameter"]) / 2.0,
                            inner_radius(
                                params["outer_diameter"], params["wall_thickness"]
                            ),
                        ))
        elif kind == "transition":
            start = vector(params["start_position"])
            axis = normalized(vector(params["axis"]))
            offset = vector(params.get("offset", [0.0, 0.0, 0.0]))
            axial_length = float(params["length"])
            for index in range(1, 8):
                fraction = index / 8.0
                # 형상 생성과 동일한 quintic smootherstep을 사용해야 probe의
                # 예상 중심/단면이 실제 loft와 같은 위치를 가리킨다.
                blend = fraction ** 3 * (
                    10.0 - 15.0 * fraction + 6.0 * fraction * fraction
                )
                outer_diameter = (
                    float(params["diameter_in"]) * (1.0 - blend)
                    + float(params["diameter_out"]) * blend
                )
                wall = (
                    float(params["wall_thickness_in"]) * (1.0 - blend)
                    + float(params["wall_thickness_out"]) * blend
                )
                candidates.append((
                    "transition_" + str(index),
                    start + axis * (axial_length * fraction) + offset * blend,
                    axis,
                    outer_diameter / 2.0,
                    inner_radius(outer_diameter, wall),
                ))
        elif kind == "junction":
            start = vector(params["start_position"])
            for index, outlet in enumerate(params.get("outlets", [])):
                end = vector(outlet["end_position"])
                outlet_length = float((end - start).Length)
                hub_radius = float(params["max_hub_radius"])
                if outlet_length <= hub_radius + MODELING_TOLERANCE:
                    raise ValueError("junction outlet does not extend beyond hub")
                for distance in (
                    hub_radius + (outlet_length - hub_radius) * 0.35,
                    hub_radius + (outlet_length - hub_radius) * 0.75,
                ):
                    fraction = distance / outlet_length
                    candidates.append((
                        "outlet_" + str(index) + "_" + str(fraction),
                        start + (end - start) * fraction,
                        end - start,
                        float(outlet["outer_diameter"]) / 2.0,
                        inner_radius(
                            outlet["outer_diameter"], outlet["wall_thickness"]
                        ),
                    ))
        elif kind == "inline_component":
            start = vector(params["start_position"])
            axis = normalized(vector(params["axis"]))
            body_center = (
                start
                + axis * (
                    float(params["body_start_offset"])
                    + float(params["body_length"]) / 2.0
                )
            )
            candidates.append((
                "component_body_mid",
                body_center,
                axis,
                float(params["body_outer_diameter"]) / 2.0,
                inner_radius(
                    params["outer_diameter"], params["wall_thickness"]
                ),
            ))
        for label, position, axis, outer_radius, bore_radius in candidates:
            sampled_internal_section_count += 1
            sampled_internal_sections_by_module[module_id] = (
                sampled_internal_sections_by_module.get(module_id, 0) + 1
            )
            failures = sample_hollow_section(
                shape, position, axis, outer_radius, bore_radius
            )
            if failures:
                wall_section_failures.append({
                    "module_id": module_id,
                    "section": label,
                    "failures": failures,
                })
    except Exception as exc:
        wall_section_failures.append({
            "module_id": module_id,
            "section": "internal_sampling",
            "error": str(exc),
        })

authored_walls = []
for module in MODULES:
    params = module["params"]
    for key in ("wall_thickness", "wall_thickness_in", "wall_thickness_out"):
        if params.get(key) is not None:
            authored_walls.append(float(params[key]))
    for outlet in params.get("outlets", []):
        if outlet.get("wall_thickness") is not None:
            authored_walls.append(float(outlet["wall_thickness"]))
minimum_wall = min(authored_walls or [0.0])
required_internal_section_module_ids = [
    module["id"]
    for module in MODULES
    if module["type"] not in ("terminate", "cap_pipe")
]
unsampled_internal_section_module_ids = [
    module_id
    for module_id in required_internal_section_module_ids
    if sampled_internal_sections_by_module.get(module_id, 0) <= 0
]
if unsampled_internal_section_module_ids:
    wall_section_failures.append({
        "module_ids": unsampled_internal_section_module_ids,
        "error": "one or more geometry-bearing modules have no internal wall sample",
    })
checks = {
    "assembly": assembly_check,
    "outer_network": outer_network_check,
    "bore_network": bore_network_check,
    "modules": module_checks,
    "centerlines": centerline_checks,
    "module_errors": module_errors,
    "assembly_errors": assembly_errors,
    "non_adjacent_overlaps": overlaps,
    "connection_failures": connection_failures,
    "terminal_bore_failures": terminal_bore_failures,
    "anchored_inlet_bore_failures": anchored_inlet_bore_failures,
    "termination_seal_failures": termination_seal_failures,
    "wall_section_failures": wall_section_failures,
    "sampled_internal_section_count": sampled_internal_section_count,
    "sampled_internal_sections_by_module": sampled_internal_sections_by_module,
    "required_internal_section_module_count": len(
        required_internal_section_module_ids
    ),
    "minimum_authored_wall_thickness": minimum_wall,
    "declared_downstream_open_port_count": len(PAYLOAD.get("open_ports", [])),
    "anchored_inlet_count": 1 if (
        PAYLOAD.get("root_port")
        and MODULES
        and MODULES[0]["type"] not in ("terminate", "cap_pipe")
    ) else 0,
}
passed = (
    bool(assembly_check.get("passed"))
    and bool(outer_network_check.get("passed"))
    and bool(bore_network_check.get("passed"))
    and not module_errors
    and not assembly_errors
    and all(item.get("passed") for item in module_checks.values())
    and all(item.get("passed") for item in centerline_checks.values())
    and not overlaps
    and not connection_failures
    and not terminal_bore_failures
    and not anchored_inlet_bore_failures
    and not termination_seal_failures
    and not wall_section_failures
    and math.isfinite(minimum_wall)
    and minimum_wall > 0.0
    and not unsampled_internal_section_module_ids
)
validation = {
    "schema_version": VALIDATION_SCHEMA_VERSION,
    "generator_version": GENERATOR_VERSION,
    "run_id": RUN_ID,
    "state_id": PAYLOAD["state_id"],
    "state_version": PAYLOAD["state_version"],
    "attempt_id": ATTEMPT_ID,
    "candidate_document": CANDIDATE_DOCUMENT,
    "candidate_shape_fingerprints": {
        obj.Name: shape_fingerprint(obj.Shape)
        for obj in doc.Objects
        if hasattr(obj, "Shape") and not obj.Shape.isNull()
    },
    "payload_digest": PAYLOAD_DIGEST,
    "module_ids": [module["id"] for module in MODULES],
    "freecad_version": App.Version(),
    "checks": checks,
    "passed": passed,
}
print("CADGEN_VALIDATION=" + json.dumps(validation, sort_keys=True, separators=(",", ":")))

import FreeCADGui as Gui
with open('/Users/jhkim/Documents/cadgen02/artifacts/notion_report/primitive_transition_changed_eccentric.freecad_validation.json', "w", encoding="utf-8") as handle:
    json.dump(validation, handle, ensure_ascii=False, indent=2, sort_keys=True)
shown_ids = ['M1']
target_ids = {'M1'}
palette = [
    (0.76, 0.80, 0.84),
    (0.34, 0.68, 0.88),
    (0.35, 0.78, 0.58),
    (0.93, 0.66, 0.25),
    (0.76, 0.45, 0.82),
]
for obj in doc.Objects:
    if hasattr(obj, "ViewObject"):
        obj.ViewObject.Visibility = False
for index, module_id in enumerate(shown_ids):
    obj = doc.getObject("solid_" + module_id)
    if obj is None:
        continue
    obj.ViewObject.Visibility = True
    if module_id in target_ids:
        obj.ViewObject.ShapeColor = (0.10, 0.54, 0.86)
        obj.ViewObject.LineColor = (0.05, 0.16, 0.25)
        obj.ViewObject.Transparency = 0
    else:
        obj.ViewObject.ShapeColor = palette[index % len(palette)]
        obj.ViewObject.LineColor = (0.20, 0.24, 0.28)
        obj.ViewObject.Transparency = 18
    obj.ViewObject.DisplayMode = "Flat Lines"
view = Gui.activeDocument().activeView()
view.setAnimationEnabled(False)
view.viewAxonometric()
view.fitAll()
view.saveImage('/Users/jhkim/Documents/cadgen02/artifacts/notion_report/primitive_transition_changed_eccentric.png', 1200, 800, "White")
try:
    from PySide import QtCore, QtGui
    source = QtGui.QImage('/Users/jhkim/Documents/cadgen02/artifacts/notion_report/primitive_transition_changed_eccentric.png')
    width = source.width()
    height = source.height()
    sample_x = list(range(0, width, max(1, width // 80)))
    def mostly_black_row(y):
        black = 0
        for x in sample_x:
            color = source.pixelColor(x, y)
            if color.red() < 12 and color.green() < 12 and color.blue() < 12:
                black += 1
        return black >= max(1, int(len(sample_x) * 0.95))
    top = 0
    while top < height and mostly_black_row(top):
        top += 1
    bottom = height - 1
    while bottom >= top and mostly_black_row(bottom):
        bottom -= 1
    cropped = source.copy(0, top, width, max(1, bottom - top + 1))
    keep_aspect = getattr(
        getattr(QtCore.Qt, "AspectRatioMode", QtCore.Qt),
        "KeepAspectRatio",
    )
    smooth = getattr(
        getattr(QtCore.Qt, "TransformationMode", QtCore.Qt),
        "SmoothTransformation",
    )
    scaled = cropped.scaled(1160, 760, keep_aspect, smooth)
    image_format = getattr(
        getattr(QtGui.QImage, "Format", QtGui.QImage),
        "Format_RGB32",
    )
    canvas = QtGui.QImage(1200, 800, image_format)
    canvas.fill(QtGui.QColor(255, 255, 255))
    painter = QtGui.QPainter(canvas)
    painter.drawImage((1200 - scaled.width()) // 2, (800 - scaled.height()) // 2, scaled)
    painter.end()
    canvas.save('/Users/jhkim/Documents/cadgen02/artifacts/notion_report/primitive_transition_changed_eccentric.png', "PNG")
except Exception as postprocess_error:
    print("CADGEN_SCREENSHOT_POSTPROCESS_WARNING=" + str(postprocess_error))
print("CADGEN_SCREENSHOT=" + '/Users/jhkim/Documents/cadgen02/artifacts/notion_report/primitive_transition_changed_eccentric.png')
print("CADGEN_KEEP_OPEN=" + str(False))
