# Generated by cadgen02.
import math
import FreeCAD as App
import Part

MODULES = [
  {
    "id": "M1",
    "type": "connector_pipe",
    "geometry_id": "solid_M1",
    "params": {
      "length": 10.0,
      "start_position": [
        0.0,
        0.0,
        0.0
      ],
      "axis": [
        1.0,
        0.0,
        0.0
      ],
      "outer_diameter": 20.0,
      "wall_thickness": 2.0,
      "end_position": [
        10.0,
        0.0,
        0.0
      ]
    },
    "ports": {
      "in": {
        "id": "M1.in",
        "position": [
          0.0,
          0.0,
          0.0
        ],
        "axis": [
          -1.0,
          -0.0,
          -0.0
        ],
        "outer_diameter": 20.0,
        "wall_thickness": 2.0,
        "connector_type": "plain"
      },
      "out": {
        "id": "M1.out",
        "position": [
          10.0,
          0.0,
          0.0
        ],
        "axis": [
          1.0,
          0.0,
          0.0
        ],
        "outer_diameter": 20.0,
        "wall_thickness": 2.0,
        "connector_type": "plain"
      }
    }
  },
  {
    "id": "M2",
    "type": "junction_pipe",
    "geometry_id": "solid_M2",
    "params": {
      "branch_count": 2,
      "branch_angles": [
        30.0,
        -45.0
      ],
      "start_position": [
        10.0,
        0.0,
        0.0
      ],
      "axis": [
        1.0,
        0.0,
        0.0
      ],
      "outer_diameter": 20.0,
      "wall_thickness": 2.0,
      "blend_radius": 12.0,
      "trunk_end": [
        50.0,
        0.0,
        0.0
      ],
      "branch_1_end": [
        10.0,
        40.0,
        0.0
      ],
      "branch_2_end": [
        10.0,
        -40.0,
        0.0
      ]
    },
    "ports": {
      "in": {
        "id": "M2.in",
        "position": [
          10.0,
          0.0,
          0.0
        ],
        "axis": [
          -1.0,
          -0.0,
          -0.0
        ],
        "outer_diameter": 20.0,
        "wall_thickness": 2.0,
        "connector_type": "plain"
      },
      "out": {
        "id": "M2.out",
        "position": [
          50.0,
          0.0,
          0.0
        ],
        "axis": [
          1.0,
          0.0,
          0.0
        ],
        "outer_diameter": 20.0,
        "wall_thickness": 2.0,
        "connector_type": "plain"
      },
      "out_1": {
        "id": "M2.out_1",
        "position": [
          10.0,
          40.0,
          0.0
        ],
        "axis": [
          0.0,
          1.0,
          0.0
        ],
        "outer_diameter": 20.0,
        "wall_thickness": 2.0,
        "connector_type": "plain"
      },
      "out_2": {
        "id": "M2.out_2",
        "position": [
          10.0,
          -40.0,
          0.0
        ],
        "axis": [
          0.0,
          -1.0,
          0.0
        ],
        "outer_diameter": 20.0,
        "wall_thickness": 2.0,
        "connector_type": "plain"
      }
    }
  },
  {
    "id": "M3",
    "type": "straight_pipe",
    "geometry_id": "solid_M3",
    "params": {
      "length": 80.0,
      "start_position": [
        50.0,
        0.0,
        0.0
      ],
      "axis": [
        1.0,
        0.0,
        0.0
      ],
      "outer_diameter": 20.0,
      "wall_thickness": 2.0,
      "end_position": [
        130.0,
        0.0,
        0.0
      ]
    },
    "ports": {
      "in": {
        "id": "M3.in",
        "position": [
          50.0,
          0.0,
          0.0
        ],
        "axis": [
          -1.0,
          -0.0,
          -0.0
        ],
        "outer_diameter": 20.0,
        "wall_thickness": 2.0,
        "connector_type": "plain"
      },
      "out": {
        "id": "M3.out",
        "position": [
          130.0,
          0.0,
          0.0
        ],
        "axis": [
          1.0,
          0.0,
          0.0
        ],
        "outer_diameter": 20.0,
        "wall_thickness": 2.0,
        "connector_type": "plain"
      }
    }
  },
  {
    "id": "M4",
    "type": "junction_pipe",
    "geometry_id": "solid_M4",
    "params": {
      "branch_count": 2,
      "branch_angles": [
        30.0,
        -45.0
      ],
      "start_position": [
        130.0,
        0.0,
        0.0
      ],
      "axis": [
        1.0,
        0.0,
        0.0
      ],
      "outer_diameter": 20.0,
      "wall_thickness": 2.0,
      "blend_radius": 12.0,
      "trunk_end": [
        170.0,
        0.0,
        0.0
      ],
      "branch_1_end": [
        130.0,
        40.0,
        0.0
      ],
      "branch_2_end": [
        130.0,
        -40.0,
        0.0
      ]
    },
    "ports": {
      "in": {
        "id": "M4.in",
        "position": [
          130.0,
          0.0,
          0.0
        ],
        "axis": [
          -1.0,
          -0.0,
          -0.0
        ],
        "outer_diameter": 20.0,
        "wall_thickness": 2.0,
        "connector_type": "plain"
      },
      "out": {
        "id": "M4.out",
        "position": [
          170.0,
          0.0,
          0.0
        ],
        "axis": [
          1.0,
          0.0,
          0.0
        ],
        "outer_diameter": 20.0,
        "wall_thickness": 2.0,
        "connector_type": "plain"
      },
      "out_1": {
        "id": "M4.out_1",
        "position": [
          130.0,
          40.0,
          0.0
        ],
        "axis": [
          0.0,
          1.0,
          0.0
        ],
        "outer_diameter": 20.0,
        "wall_thickness": 2.0,
        "connector_type": "plain"
      },
      "out_2": {
        "id": "M4.out_2",
        "position": [
          130.0,
          -40.0,
          0.0
        ],
        "axis": [
          0.0,
          -1.0,
          0.0
        ],
        "outer_diameter": 20.0,
        "wall_thickness": 2.0,
        "connector_type": "plain"
      }
    }
  },
  {
    "id": "M5",
    "type": "cap_pipe",
    "geometry_id": "solid_M5",
    "params": {
      "end_type": "open",
      "outer_diameter": 20.0,
      "wall_thickness": 2.0,
      "start_position": [
        10.0,
        40.0,
        0.0
      ],
      "axis": [
        0.0,
        1.0,
        0.0
      ],
      "cap_thickness": 3.0,
      "end_position": [
        10.0,
        40.0,
        0.0
      ]
    },
    "ports": {
      "in": {
        "id": "M5.in",
        "position": [
          10.0,
          40.0,
          0.0
        ],
        "axis": [
          -0.0,
          -1.0,
          -0.0
        ],
        "outer_diameter": 20.0,
        "wall_thickness": 2.0,
        "connector_type": "plain"
      }
    }
  }
]


def vector(values):
    return App.Vector(float(values[0]), float(values[1]), float(values[2]))


def make_tube_between(start_values, end_values, outer_diameter, wall_thickness):
    start = vector(start_values)
    end = vector(end_values)
    axis = end - start
    height = axis.Length
    if height <= 0:
        return None
    axis.normalize()
    outer_radius = float(outer_diameter) / 2.0
    outer = Part.makeCylinder(outer_radius, height, start, axis)
    if float(wall_thickness) <= 0:
        return outer
    inner_radius = max(outer_radius - float(wall_thickness), 0.001)
    inner = Part.makeCylinder(inner_radius, height + 2.0, start - axis, axis)
    return outer.cut(inner)


def make_reducer(module):
    params = module["params"]
    start = vector(params["start_position"])
    end = vector(params["end_position"])
    axis = end - start
    height = axis.Length
    if height <= 0:
        return None
    axis.normalize()
    outer = Part.makeCone(
        float(params["diameter_in"]) / 2.0,
        float(params["diameter_out"]) / 2.0,
        height,
        start,
        axis,
    )
    inner = Part.makeCone(
        max(float(params["diameter_in"]) / 2.0 - float(params["wall_thickness_in"]), 0.001),
        max(float(params["diameter_out"]) / 2.0 - float(params["wall_thickness_out"]), 0.001),
        height + 2.0,
        start - axis,
        axis,
    )
    return outer.cut(inner)


def make_cap(module):
    params = module["params"]
    start = vector(params["start_position"])
    axis = vector(params["axis"])
    axis.normalize()
    outer_radius = float(params["outer_diameter"]) / 2.0
    thickness = float(params.get("cap_thickness", params["wall_thickness"]))
    return Part.makeCylinder(outer_radius, thickness, start, axis)


def make_module(module):
    params = module["params"]
    kind = module["type"]
    if kind in ("straight_pipe", "connector_pipe"):
        return make_tube_between(
            params["start_position"],
            params["end_position"],
            params["outer_diameter"],
            params["wall_thickness"],
        )
    if kind == "bend_pipe":
        points = params["path_points"]
        segments = []
        for index in range(len(points) - 1):
            segment = make_tube_between(
                points[index],
                points[index + 1],
                params["outer_diameter"],
                params["wall_thickness"],
            )
            if segment is not None:
                segments.append(segment)
        if not segments:
            return None
        result = segments[0]
        for segment in segments[1:]:
            result = result.fuse(segment)
        return result
    if kind == "reducer_pipe":
        return make_reducer(module)
    if kind == "junction_pipe":
        shapes = []
        trunk = make_tube_between(
            params["start_position"],
            params["trunk_end"],
            params["outer_diameter"],
            params["wall_thickness"],
        )
        if trunk is not None:
            shapes.append(trunk)
        for key, value in params.items():
            if key.startswith("branch_") and key.endswith("_end"):
                branch = make_tube_between(
                    params["start_position"],
                    value,
                    params["outer_diameter"],
                    params["wall_thickness"],
                )
                if branch is not None:
                    shapes.append(branch)
        if not shapes:
            return None
        result = shapes[0]
        for shape in shapes[1:]:
            result = result.fuse(shape)
        return result
    if kind == "cap_pipe":
        return make_cap(module)
    return None


doc = App.ActiveDocument or App.newDocument("CadGenPipe")
shapes = []
for module in MODULES:
    shape = make_module(module)
    if shape is not None:
        shapes.append(shape)

if shapes:
    assembly = shapes[0]
    for shape in shapes[1:]:
        assembly = assembly.fuse(shape)
    obj = doc.addObject("Part::Feature", "PipeAssembly")
    obj.Shape = assembly
    doc.recompute()
