# Generated by cadgen02.
import FreeCAD as App
import Part

MODULES = [
  {
    "id": "M1",
    "type": "junction_pipe",
    "geometry_id": "solid_M1",
    "params": {
      "branch_count": 2,
      "branch_angles": [
        45,
        -45
      ],
      "length": 40.0,
      "start_position": [
        0.0,
        0.0,
        0.0
      ],
      "axis": [
        1.0,
        0.0,
        0.0
      ],
      "outer_diameter": 20.0,
      "wall_thickness": 2.0,
      "blend_radius": 12.0,
      "trunk_end": [
        40.0,
        0.0,
        0.0
      ],
      "branch_1_end": [
        28.284271247461902,
        -28.2842712474619,
        0.0
      ],
      "branch_2_end": [
        28.284271247461902,
        28.2842712474619,
        0.0
      ]
    },
    "ports": {
      "in": {
        "id": "M1.in",
        "position": [
          0.0,
          0.0,
          0.0
        ],
        "axis": [
          -1.0,
          -0.0,
          -0.0
        ],
        "outer_diameter": 20.0,
        "wall_thickness": 2.0,
        "connector_type": "plain"
      },
      "out": {
        "id": "M1.out",
        "position": [
          40.0,
          0.0,
          0.0
        ],
        "axis": [
          1.0,
          0.0,
          0.0
        ],
        "outer_diameter": 20.0,
        "wall_thickness": 2.0,
        "connector_type": "plain"
      },
      "out_1": {
        "id": "M1.out_1",
        "position": [
          28.284271247461902,
          -28.2842712474619,
          0.0
        ],
        "axis": [
          0.7071067811865476,
          -0.7071067811865475,
          0.0
        ],
        "outer_diameter": 20.0,
        "wall_thickness": 2.0,
        "connector_type": "plain"
      },
      "out_2": {
        "id": "M1.out_2",
        "position": [
          28.284271247461902,
          28.2842712474619,
          0.0
        ],
        "axis": [
          0.7071067811865476,
          0.7071067811865475,
          0.0
        ],
        "outer_diameter": 20.0,
        "wall_thickness": 2.0,
        "connector_type": "plain"
      }
    }
  },
  {
    "id": "M2",
    "type": "straight_pipe",
    "geometry_id": "solid_M2",
    "params": {
      "length": 60.0,
      "direction": "+X",
      "start_position": [
        40.0,
        0.0,
        0.0
      ],
      "axis": [
        1.0,
        0.0,
        0.0
      ],
      "outer_diameter": 20.0,
      "wall_thickness": 2.0,
      "end_position": [
        100.0,
        0.0,
        0.0
      ]
    },
    "ports": {
      "in": {
        "id": "M2.in",
        "position": [
          40.0,
          0.0,
          0.0
        ],
        "axis": [
          -1.0,
          -0.0,
          -0.0
        ],
        "outer_diameter": 20.0,
        "wall_thickness": 2.0,
        "connector_type": "plain"
      },
      "out": {
        "id": "M2.out",
        "position": [
          100.0,
          0.0,
          0.0
        ],
        "axis": [
          1.0,
          0.0,
          0.0
        ],
        "outer_diameter": 20.0,
        "wall_thickness": 2.0,
        "connector_type": "plain"
      }
    }
  },
  {
    "id": "M3",
    "type": "junction_pipe",
    "geometry_id": "solid_M3",
    "params": {
      "branch_count": 2,
      "branch_angles": [
        45.0,
        -45.0
      ],
      "length": 40.0,
      "blend_radius": 10.0,
      "start_position": [
        100.0,
        0.0,
        0.0
      ],
      "axis": [
        1.0,
        0.0,
        0.0
      ],
      "outer_diameter": 20.0,
      "wall_thickness": 2.0,
      "trunk_end": [
        140.0,
        0.0,
        0.0
      ],
      "branch_1_end": [
        128.2842712474619,
        -28.2842712474619,
        0.0
      ],
      "branch_2_end": [
        128.2842712474619,
        28.2842712474619,
        0.0
      ]
    },
    "ports": {
      "in": {
        "id": "M3.in",
        "position": [
          100.0,
          0.0,
          0.0
        ],
        "axis": [
          -1.0,
          -0.0,
          -0.0
        ],
        "outer_diameter": 20.0,
        "wall_thickness": 2.0,
        "connector_type": "plain"
      },
      "out": {
        "id": "M3.out",
        "position": [
          140.0,
          0.0,
          0.0
        ],
        "axis": [
          1.0,
          0.0,
          0.0
        ],
        "outer_diameter": 20.0,
        "wall_thickness": 2.0,
        "connector_type": "plain"
      },
      "out_1": {
        "id": "M3.out_1",
        "position": [
          128.2842712474619,
          -28.2842712474619,
          0.0
        ],
        "axis": [
          0.7071067811865476,
          -0.7071067811865475,
          0.0
        ],
        "outer_diameter": 20.0,
        "wall_thickness": 2.0,
        "connector_type": "plain"
      },
      "out_2": {
        "id": "M3.out_2",
        "position": [
          128.2842712474619,
          28.2842712474619,
          0.0
        ],
        "axis": [
          0.7071067811865476,
          0.7071067811865475,
          0.0
        ],
        "outer_diameter": 20.0,
        "wall_thickness": 2.0,
        "connector_type": "plain"
      }
    }
  },
  {
    "id": "M4",
    "type": "cap_pipe",
    "geometry_id": "solid_M4",
    "params": {
      "end_type": "open",
      "start_position": [
        28.284271247461902,
        -28.2842712474619,
        0.0
      ],
      "axis": [
        0.7071067811865476,
        -0.7071067811865475,
        0.0
      ],
      "outer_diameter": 20.0,
      "wall_thickness": 2.0,
      "cap_thickness": 3.0,
      "end_position": [
        28.284271247461902,
        -28.2842712474619,
        0.0
      ]
    },
    "ports": {
      "in": {
        "id": "M4.in",
        "position": [
          28.284271247461902,
          -28.2842712474619,
          0.0
        ],
        "axis": [
          -0.7071067811865476,
          0.7071067811865475,
          -0.0
        ],
        "outer_diameter": 20.0,
        "wall_thickness": 2.0,
        "connector_type": "plain"
      },
      "out": {
        "id": "M4.out",
        "position": [
          28.284271247461902,
          -28.2842712474619,
          0.0
        ],
        "axis": [
          0.7071067811865476,
          -0.7071067811865475,
          0.0
        ],
        "outer_diameter": 20.0,
        "wall_thickness": 2.0,
        "connector_type": "plain"
      }
    }
  }
]
BORE_EXTENSION = 2.0


def vector(values):
    return App.Vector(float(values[0]), float(values[1]), float(values[2]))


def normalized(value):
    result = App.Vector(value.x, value.y, value.z)
    if result.Length <= 1e-9:
        return App.Vector(1.0, 0.0, 0.0)
    result.normalize()
    return result


def safe_radius(value):
    return max(float(value), 0.001)


def inner_radius(outer_diameter, wall_thickness):
    return safe_radius(float(outer_diameter) / 2.0 - float(wall_thickness))


def make_cylinder_between(start_values, end_values, radius, extra=0.0):
    start = vector(start_values)
    end = vector(end_values)
    axis = end - start
    height = axis.Length
    if height <= 1e-9:
        return None
    axis.normalize()
    extra = max(float(extra), 0.0)
    return Part.makeCylinder(
        safe_radius(radius),
        height + extra * 2.0,
        start - axis * extra,
        axis,
    )


def make_cone_between(start_values, end_values, start_radius, end_radius, extra=0.0):
    start = vector(start_values)
    end = vector(end_values)
    axis = end - start
    height = axis.Length
    if height <= 1e-9:
        return None
    axis.normalize()
    extra = max(float(extra), 0.0)
    slope = (float(end_radius) - float(start_radius)) / height
    extended_start_radius = safe_radius(float(start_radius) - slope * extra)
    extended_end_radius = safe_radius(float(end_radius) + slope * extra)
    return Part.makeCone(
        extended_start_radius,
        extended_end_radius,
        height + extra * 2.0,
        start - axis * extra,
        axis,
    )


def make_segment_chain(points, radius, extra=0.0):
    shapes = []
    for index in range(len(points) - 1):
        shape = make_cylinder_between(points[index], points[index + 1], radius, extra)
        if shape is not None:
            shapes.append(shape)
    return fuse_shapes(shapes)


def make_bend_shape(points, radius, extra=0.0):
    return make_segment_chain(points, radius, extra)


def fuse_shapes(shapes):
    result = None
    for shape in shapes:
        if shape is None:
            continue
        if result is None:
            result = shape
            continue
        result = result.fuse(shape)
        try:
            result = result.removeSplitter()
        except Exception:
            pass
    return result


def cut_shapes(base, cutters):
    result = base
    for cutter in cutters:
        if cutter is None:
            continue
        result = result.cut(cutter)
        try:
            result = result.removeSplitter()
        except Exception:
            pass
    return result


def add_tube_between(module, start_values, end_values, outer_radius, bore_radius, outer_shapes, inner_cutters):
    outer_shapes.append(make_cylinder_between(start_values, end_values, outer_radius))
    inner_cutters.append(
        make_cylinder_between(start_values, end_values, bore_radius, BORE_EXTENSION)
    )


def collect_module_shapes(module, outer_shapes, inner_cutters):
    params = module["params"]
    kind = module["type"]
    if kind == "straight_pipe":
        add_tube_between(
            module,
            params["start_position"],
            params["end_position"],
            float(params["outer_diameter"]) / 2.0,
            inner_radius(params["outer_diameter"], params["wall_thickness"]),
            outer_shapes,
            inner_cutters,
        )
        return

    if kind == "connector_pipe":
        outer_shapes.append(
            make_cylinder_between(
                params["start_position"],
                params["end_position"],
                float(params.get("coupling_outer_diameter", params["outer_diameter"])) / 2.0,
                float(params.get("sleeve_overlap", 0.0)),
            )
        )
        inner_cutters.append(
            make_cylinder_between(
                params["start_position"],
                params["end_position"],
                inner_radius(params["outer_diameter"], params["wall_thickness"]),
                BORE_EXTENSION,
            )
        )
        return

    if kind == "bend_pipe":
        points = params["path_points"]
        outer_shapes.append(
            make_bend_shape(points, float(params["outer_diameter"]) / 2.0)
        )
        inner_cutters.append(
            make_bend_shape(
                points,
                inner_radius(params["outer_diameter"], params["wall_thickness"]),
                BORE_EXTENSION,
            )
        )
        return

    if kind == "reducer_pipe":
        outer_shapes.append(
            make_cone_between(
                params["start_position"],
                params["end_position"],
                float(params["diameter_in"]) / 2.0,
                float(params["diameter_out"]) / 2.0,
            )
        )
        inner_cutters.append(
            make_cone_between(
                params["start_position"],
                params["end_position"],
                inner_radius(params["diameter_in"], params["wall_thickness_in"]),
                inner_radius(params["diameter_out"], params["wall_thickness_out"]),
                BORE_EXTENSION,
            )
        )
        return

    if kind == "junction_pipe":
        bore_radius = inner_radius(params["outer_diameter"], params["wall_thickness"])
        outer_radius = float(params["outer_diameter"]) / 2.0
        add_tube_between(
            module,
            params["start_position"],
            params["trunk_end"],
            outer_radius,
            bore_radius,
            outer_shapes,
            inner_cutters,
        )
        for key, value in params.items():
            if key.startswith("branch_") and key.endswith("_end"):
                add_tube_between(
                    module,
                    params["start_position"],
                    value,
                    outer_radius,
                    bore_radius,
                    outer_shapes,
                    inner_cutters,
                )
        return

    if kind == "cap_pipe":
        if params.get("end_type") == "open":
            return
        start = vector(params["start_position"])
        axis = normalized(vector(params["axis"]))
        outer_radius = float(params["outer_diameter"]) / 2.0
        thickness = float(params.get("cap_thickness", params["wall_thickness"]))
        outer_shapes.append(Part.makeCylinder(outer_radius, thickness, start, axis))
        return


doc = App.newDocument("CadGenPipe")
outer_shapes = []
inner_cutters = []
for module in MODULES:
    collect_module_shapes(module, outer_shapes, inner_cutters)

outer_assembly = fuse_shapes(outer_shapes)
if outer_assembly is None:
    raise RuntimeError("No pipe outer geometry was generated.")

assembly = cut_shapes(outer_assembly, inner_cutters)

try:
    assembly = assembly.removeSplitter()
except Exception:
    pass

obj = doc.addObject("Part::Feature", "PipeAssembly")
obj.Shape = assembly
doc.recompute()
